version: "3.8"

services:
    mysqldb:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./.docker/storage/mysql:/var/lib/mysql

    app:
        build: .
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - .docker/www.conf:/etc/php8/php-fpm.d/www.conf
            - .docker/php.ini:/etc/php8/conf.d/php.ini
            - .docker/opcache.ini:/etc/php8/conf.d/opcache.ini
        depends_on:
            - mysqldb

    nginx:
        image: nginx:1.21-alpine
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./.docker/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/certs:/etc/ssl/certs
        depends_on:
            - app
        ports:
            - "80:80"
            - "443:443"

    portainer:
        image: portainer/portainer-ce
        volumes:
            - ./.docker/storage/portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "9000:9000"
